apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 71-master-motd-http
  labels:
    machineconfiguration.openshift.io/role: master
spec:
  config:
    ignition:
      version: 3.4.0
    storage:
      files:
      - path: /etc/motd
        mode: 0444
        overwrite: true
        contents:
          source: http://192.168.0.170:8080/motd.txt
